### ISSUE TITLE
Import error on Linux

### ISSUE THREAD

**Issue by plimkilde** [Kortforsyningen/DHMQC#42]
Tests currently fail under Linux with the following message. Presumably, one of the Conda packages has broken dependency handling recently.

```
E
======================================================================
ERROR: Failure: ImportError (libpoppler.so.76: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/peter/develop/DHMQC/tests.py", line 6, in <module>
    from qc.db import report
  File "/home/peter/develop/DHMQC/qc/db/report.py", line 28, in <module>
    from osgeo import ogr, osr, gdal
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/peter/miniconda3/envs/dhmqc_test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
```

**Comment by plimkilde** [comment]
Turns out `libpoppler` and `libkea` are currently not findable to GDAL with the recommended Conda environment for DHMQC. There is no problem in an environment with only `gdal` installed.

```
$ ldd ./libgdal.so | grep 'not found'
	libpoppler.so.76 => not found
	libkea.so.1.4.7 => not found
```
